version: '3.4'

services:
  photonauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:PgSql=Server=s_postgresql;Port=5432;Database=photon_auth;User Id=postgres;Password=your_pass;
    ports:
      - "3008:80"
    depends_on:
      - p_postgresql
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  p_postgresql:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_pass
      PGDATA: /data/postgres
    volumes:
      - data-photonauth:/data/postgres
    ports:
      - "5431:5432"
    #networks:
    #  - postgres
    restart: unless-stopped
volumes:
  data-photonauth: