version: '3.4'

services:
  photonauth:
    image: ${DOCKER_REGISTRY-}photonauth
    build:
      context: .
      dockerfile: PhotonAuth/Dockerfile

  p_postgresql:
    container_name: p_postgresql
    image: postgres